name: Create Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Makefile Rule
      run: |
        COMMIT_HASH=${{ github.sha }}
        BRANCH_NAME=${{ github.ref_name }}

        if [ "$BRANCH_NAME" = "develop" ]; then
          IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:develop"
        else
          IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:${COMMIT_HASH}"
        fi
      
        docker build -t "${IMAGE_NAME}" .

    - name: Push Docker image
      run: |
        COMMIT_HASH=${{ github.sha }}
        BRANCH_NAME=${{ github.ref_name }}

        if [ "$BRANCH_NAME" = "develop" ]; then
          IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:develop"
        else
          IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:${COMMIT_HASH}"
        fi

        docker push "${IMAGE_NAME}"