name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Makefile Rule
      run: |
        COMMIT_HASH=${{ github.sha }}
        IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:${COMMIT_HASH}"
        docker build . --tag "${IMAGE_NAME}" .

    - name: Push Docker image
      run: |
        COMMIT_HASH=${{ github.sha }}
        IMAGE_NAME="ghcr.io/mydigitwinnl/federated_cvdm_training_poc:${COMMIT_HASH}"
        docker push "${IMAGE_NAME}"



        11371  docker build . -t ghcr.io/mydigitwinnl/federated_cvdm_training_poc
11372  docker ls
11373  docker ps
11374  docker images
11375  docker push ghcr.io/mydigitwinnl/federated_cvdm_training_poc:latest